# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170422_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='importance',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='attached',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
