# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170426_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldierdetail',
            old_name='sevice_num',
            new_name='service_num',
        ),
        migrations.AlterField(
            model_name='soldier',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
