# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170427_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldierdetail',
            name='birth',
            field=models.DateField(),
        ),
    ]
