# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20170428_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_approved', models.NullBooleanField()),
                ('n1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n1', to=settings.AUTH_USER_MODEL)),
                ('n2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='n2', to=settings.AUTH_USER_MODEL)),
                ('n3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='n3', to=settings.AUTH_USER_MODEL)),
                ('n4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='n4', to=settings.AUTH_USER_MODEL)),
                ('n5', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='n5', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_approved', models.NullBooleanField()),
                ('completed_date', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counsel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('contents', models.TextField()),
                ('plan', models.TextField()),
                ('attached', models.FileField(blank=True, upload_to='counsels/')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Soldier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
