# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20170506_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='counsel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Counsel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approval',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvalunit',
            name='approval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Approval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvalunit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
