# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20170506_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_approved', models.NullBooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('counsel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Counsel')),
                ('n1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n1', to=settings.AUTH_USER_MODEL)),
                ('n2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='n2', to=settings.AUTH_USER_MODEL)),
                ('n3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='n3', to=settings.AUTH_USER_MODEL)),
                ('n4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='n4', to=settings.AUTH_USER_MODEL)),
                ('n5', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='n5', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
