# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='n2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='n3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='n4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='n5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n5', to=settings.AUTH_USER_MODEL),
        ),
    ]
