# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20170506_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_approved', models.NullBooleanField()),
                ('completed_date', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(null=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Approval')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
