# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_approvalunit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sol_user_rel',
            unique_together=set([('soldier', 'user')]),
        ),
    ]
