# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170507_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
