# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170521_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
